spring.application.name=shoplite

spring.datasource.url=jdbc:mysql://localhost:3306/shoplitedb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
shoplite.jwt.base64-secret=c2hvcGxpdGUtc2VjcmV0LWtleS10aGF0LXJlYWxseS1tdXN0LWJlLWF0LWxlYXN0LTUxMi1iaXRzLWxvbmctZm9yLW1hYy1hbGdvcml0aG0taHM1MTItMTIzNDU2Nzg5MA==
shoplite.jwt.access-token-expiration=86400
shoplite.jwt.refresh-token-expiration=604800

logging.level.org.springframework.security=WARN
logging.level.org.springframework.web.servlet.mvc.method.annotation=DEBUG

# SpringDoc OpenAPI
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.disable-swagger-default-url=true
